baseURL = "https://nihaal.me"
languageCode = "en-us"
title = "Nihaal"
theme="archie"
copyright = ""
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

paginate=5 # articles per page

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Notes, musings and what not"
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nifey"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://in.linkedin.com/in/abdun-nihaal-289272143"

[[params.social]]
name = "Google Scholar"
icon = "book"
url = "https://scholar.google.com/citations?user=7OgnEeUAAAAJ"

# Main menu Items

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
